---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmh-generator-operator
  namespace: metal3-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bmh-generator-operator
rules:
# For managing our CRD
- apiGroups: ["infra.example.com"]
  resources: ["baremetalhostgenerators"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["infra.example.com"]
  resources: ["baremetalhostgenerators/status"]
  verbs: ["patch", "update"]
# For creating BareMetalHosts
- apiGroups: ["metal3.io"]
  resources: ["baremetalhosts"]
  verbs: ["create", "get", "list", "watch"]
# For creating BMC secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "watch"]
# For Kopf framework
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bmh-generator-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bmh-generator-operator
subjects:
- kind: ServiceAccount
  name: bmh-generator-operator
  namespace: metal3-system